### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by hryniuk** [okraits/omodoro#9]
What do you think about changing arguments format to make possible updating only part of them?

I mean that it will be really nice for users to simply call omodoro for e.g. 5 cycles and use the rest of settings from the config. Example (`-n` means number of pomodori, `-l` - length of long breaks):

```
python omodoro -n 10 -l 20
```

**Comment by okraits** [comment]
I don't really want to add the functionality you mentioned because it adds complexity to the code which doesn't bring real benefits.

The user can use the settings from the config file or provide all settings on the commandline (for single runs of omodoro for example). A mixture of both is too much finetuning for such a simple tool.
